"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = '''
$directory$git_branch$character
'''

[directory]
truncate_to_repo = false
truncation_length = 0
format = "[$path](blue) "

[git_branch]
format = "[on](bright-black) [$branch]() "
symbol = ""

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](green)"
vimcmd_symbol = "[\\$](red)"
