"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = '''
$username:$shell:$directory:$git_branch $character
'''

[username]
show_always = true
format = "[$user]()"

[shell]
disabled = false
format = "$indicator"

[directory]
truncate_to_repo = false
truncation_length = 0
format = "[$path]()"

[git_branch]
format = "[$branch]()"
symbol = ""

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](green)"
